### ISSUE TITLE
It returns only 1 result

### ISSUE THREAD

**Issue by wu-changxing** [Olament/Hanzi2PinyinEngine#3]
Hi Olament, thanks for sharing the project.
I've cloned and checked that, but I found that the program only gave a result as the screenshot below.
The code in SMLGraph.swift also showed that It only gave a result as below.
```swift
// code in SLMGraph.swift , func of makSentence()
     func makeSentence() -> Solution {
        self.distanceTo[0] = 0 // set the starting vertex to zero

......
            while currentIndex != 0 {
                solution.pinyin = self.vertices[currentIndex].data!.pinyinSequence!.pinyinSequence + solution.pinyin
                solution.sentence = self.vertices[currentIndex].data!.phrase! + solution.sentence
                currentIndex = self.edgeTo[currentIndex]!.from.id
            }

.......
return solution
}


```

So, I just wonder that is this the final version of your code? Would you mind to update your **final version of code** which can give the multiple results?

**Thanks a lot!** 

![simulator_screenshot_494AC6CD-37DD-4317-9B04-53F95D0C8413](https://user-images.githubusercontent.com/74539201/99351602-e8959c80-28db-11eb-89a7-3e333745d021.png)

**Comment by Olament** [comment]
I switched from showing top-K results to only one result because of performance concerns. Most Pinyin input method out there shows only one sentence so no need for computing sentence you will never use. Plus, finding the shortest path in DAG takes O(n+m) time while finding top-k shortest path takes O(m + knlogn) time. If you still want to show top-k results, check 387eca10e64da82246a2c79e8b124710968738fb

**Comment by wu-changxing** [comment]
I rewrote the top-k shortest part yesterday, but thanks a lot for your reply, your code is more elegant.
You're right, it will take (m+nlg(n)) time. I'll try to find some way to optimize the topological-sort part or try the other paths to start my pinyin engine.
thank you again.
